name: Publish psychmatch docker images

on:
  # Trigger the workflow on push
  # but only for the master branch
  push:
    branches:
      - master

  # runs once every month
  schedule:
    - cron: "0 3 1 * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  push_to_registry:
    name: Push psychmatch docker images to GitHub Packages
    runs-on: ubuntu-latest
    
    steps:
      - 
        name: Check out the repo
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build psychmatch backend docker
        uses: docker/build-push-action@v2
        with:
          context: ./backend
          target: psychmatch-backend-deploy
          load: true
          tags: |
            ghcr.io/jimmylevell/psychmatch/psychmatch_backend:latest
      -
        name: Build psychmatch frontend docker
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          target: psychmatch-frontend-deploy
          load: true
          tags: |
            ghcr.io/jimmylevell/psychmatch/psychmatch_frontend:latest
      -
        name: Build psychmatch nlp-model docker
        uses: docker/build-push-action@v2
        with:
          context: ./nlp-model
          target: psychmatch-nlp-model-deploy
          load: true
          tags: |
            ghcr.io/jimmylevell/psychmatch/psychmatch_nlp_model:latest
      -
        name: Push psychmatch backend docker
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./backend
          target: psychmatch-backend-deploy
          tags: |
            ghcr.io/jimmylevell/psychmatch/psychmatch_backend:latest
      -
        name: Push psychmatch frontend docker
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./frontend
          target: psychmatch-frontend-deploy
          tags: |
            ghcr.io/jimmylevell/psychmatch/psychmatch_frontend:latest
      -
        name: Push psychmatch nlp-model docker
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./nlp-model
          target: psychmatch-nlp-model-deploy
          tags: |
            ghcr.io/jimmylevell/psychmatch/psychmatch_nlp_model:latest
      -
        name: Deploy to swarm
        uses: wshihadeh/docker-deployment-action@v2
        with:
          remote_docker_host: worker@levell.ch
          ssh_private_key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
          ssh_public_key: ${{ secrets.DOCKER_SSH_PUBLIC_KEY }}
          deployment_mode: docker-swarm
          copy_stack_file: true
          pull_images_first: true
          deploy_path: /home/worker/levell/psychmatch
          stack_file_name: docker-compose.prod.yml
          args: --with-registry-auth --prune psychmatch